# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

build:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  stage: build
  image: node:lts-alpine
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - dist/game2gather-ui

deploy:
  stage: deploy
  script:
    - apk add --update npm
    - npm install -g heroku
    - docker build -t registry.heroku.com/game2gather/web:latest -t $CI_REGISTRY/game-2-gather/frontend/game-2-gather-frontend:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/game-2-gather/frontend/game-2-gather-frontend:latest
    - heroku container:login
    - docker push registry.heroku.com/game2gather/web:latest
    - heroku container:release web -a game2gather
