workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle/wrapper
      - .gradle/caches
  stage: build
  image: openjdk:17-jdk-alpine
  script:
    - chmod +x ./gradlew
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - ./gradlew bootJar
  artifacts:
    paths:
      - build/libs/*.jar

deploy:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/game-2-gather/backend/game-2-gather-backend:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/game-2-gather/backend/game-2-gather-backend:latest
